/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface BlocklistInterface extends utils.Interface {
  functions: {
    "addHostName(string)": FunctionFragment;
    "blockcount()": FunctionFragment;
    "blocklist(uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "addHostName", values: [string]): string;
  encodeFunctionData(
    functionFragment: "blockcount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blocklist",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addHostName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "blockcount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "blocklist", data: BytesLike): Result;

  events: {};
}

export interface Blocklist extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BlocklistInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addHostName(
      _hostName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    blockcount(overrides?: CallOverrides): Promise<[BigNumber]>;

    blocklist(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  addHostName(
    _hostName: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  blockcount(overrides?: CallOverrides): Promise<BigNumber>;

  blocklist(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    addHostName(_hostName: string, overrides?: CallOverrides): Promise<void>;

    blockcount(overrides?: CallOverrides): Promise<BigNumber>;

    blocklist(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    addHostName(
      _hostName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    blockcount(overrides?: CallOverrides): Promise<BigNumber>;

    blocklist(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addHostName(
      _hostName: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    blockcount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    blocklist(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
