/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Blocklist } from "./Blocklist";

export { Blocklist__factory } from "./factories/Blocklist__factory";
